# CI tests using GitHub Actions

name: CI

on:
  push:

    branches:
      - '**'

    paths-ignore:
      - '*.md'
      - '*.ignore'
      - LICENSE

  pull_request:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  
  #=======================================================================================================
  
  CI-TEST:
    
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
      - name: Rtest
        run: |
          Rscript --vanilla R/tests.R
      - name: Commit plot
        run: |
          git config --global user.name 'atpoint'
          git config --global user.email 'atpoint@users.noreply.github.com'
          mkdir -p misc && mv heatmap.png misc/heatmap.png
          git add misc/heatmap.png
          git commit -am "commit plot from ci test"
          git push    



